(() => {
'use strict';
const X=window.TTEX;if(!X)return;const {db,esc,toast}=X;
let anchor=new Date(),view='week',events=[],students=[];anchor.setHours(12,0,0,0);
const css=document.createElement('style');css.textContent=`
.tt-calbar{display:grid;grid-template-columns:auto 1fr auto;gap:12px;align-items:center;margin-bottom:14px}.tt-calnav,.tt-calactions{display:flex;gap:7px;align-items:center}.tt-caltitle{display:flex;gap:10px;align-items:center;justify-content:center}.tt-caltitle strong{font-size:18px}.tt-caltitle input{width:auto}.tt-viewtoggle{display:flex;background:#eef2f7;padding:3px;border-radius:9px}.tt-viewtoggle button{border:0;background:transparent;padding:7px 10px;border-radius:7px;font-size:10px;font-weight:800;cursor:pointer}.tt-viewtoggle button.active{background:#fff;box-shadow:0 1px 4px rgba(15,23,42,.12)}.tt-month-head,.tt-month{display:grid;grid-template-columns:repeat(7,minmax(0,1fr))}.tt-month-head span{text-align:center;font-size:9px;font-weight:800;color:var(--muted);padding:6px}.tt-month{gap:1px;background:var(--border);border:1px solid var(--border);border-radius:13px;overflow:hidden}.tt-mday{border:0;background:#fff;min-height:112px;padding:7px;text-align:left;cursor:pointer;color:var(--text)}.tt-mday.out{background:#f8fafc;color:#9aa5b6}.tt-mday.today .tt-daynum{background:#2d66ed;color:#fff}.tt-daynum{display:grid;place-items:center;width:24px;height:24px;border-radius:50%;font-size:10px;font-weight:800}.tt-mevents{display:grid;gap:3px;margin-top:5px}.tt-mevent{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;padding:3px 4px;border-radius:5px;background:#edf3ff;color:#2459bb;font-size:8px;font-weight:700}.tt-more{font-size:8px;color:var(--muted)}.calendar .day.tt-today{outline:2px solid rgba(45,102,237,.25);outline-offset:-2px}.calendar .event{cursor:pointer;min-width:0;overflow:hidden}.calendar .event:hover{box-shadow:0 0 0 2px rgba(37,99,235,.12)}.calendar .event-actions button{position:relative;z-index:2}.calendar .recurrence-chip{display:inline-flex;align-items:center;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tt-recur-short{display:none}
@media(max-width:780px){.tt-calbar{display:flex;flex-direction:column;align-items:stretch}.tt-caltitle{order:1;justify-content:space-between}.tt-calnav{order:2}.tt-calactions{order:3;justify-content:space-between}.tt-mday{min-height:78px;padding:4px}.tt-mevent{font-size:7px}.tt-caltitle strong{font-size:15px}.calendar{grid-template-columns:repeat(7,minmax(112px,1fr))}.calendar .day{padding:8px}.calendar .event{padding:7px;font-size:10px}.calendar .recurrence-chip{font-size:8px;padding:2px 5px;margin-top:4px}.tt-recur-long{display:none}.tt-recur-short{display:inline}}
`;document.head.appendChild(css);
const recur=v=>({none:'Não repetir',weekly:'Semanalmente',biweekly:'Quinzenalmente',monthly:'Mensalmente'})[v]||'Não repetir';
const recurShort=v=>({none:'',weekly:'Semanal',biweekly:'Quinzenal',monthly:'Mensal'})[v]||'';
function step(d,r){const x=new Date(d);if(r==='weekly')x.setDate(x.getDate()+7);else if(r==='biweekly')x.setDate(x.getDate()+14);else if(r==='monthly'){const day=x.getDate();x.setDate(1);x.setMonth(x.getMonth()+1);x.setDate(Math.min(day,new Date(x.getFullYear(),x.getMonth()+1,0).getDate()))}else return null;return x}
function isExcluded(ev,d){const t=d.getTime();return (Array.isArray(ev.recurrence_exceptions)?ev.recurrence_exceptions:[]).some(x=>Math.abs(new Date(x).getTime()-t)<1000)}
function occ(ev,a,b){const s=new Date(ev.starts_at),e=new Date(ev.ends_at),dur=e-s,r=ev.recurrence||'none',until=ev.recurrence_until?new Date(`${ev.recurrence_until}T23:59:59`):null,out=[];if(r==='none'){if(s<=b&&e>=a)out.push({...ev,_start:s});return out}let cur=s,n=0;while(cur<=b&&n++<800){if((!until||cur<=until)&&new Date(cur.getTime()+dur)>=a&&!isExcluded(ev,cur))out.push({...ev,_start:new Date(cur)});const nx=step(cur,r);if(!nx)break;cur=nx;if(until&&cur>until)break}return out}
function monday(d){const x=new Date(d),wd=(x.getDay()+6)%7;x.setDate(x.getDate()-wd);x.setHours(0,0,0,0);return x}function iso(d){const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)}function student(id){return students.find(s=>s.id===id)}
function toolbar(title){return`<div class="tt-calbar"><div class="tt-calnav"><button class="secondary" onclick="ttCalPrev()">‹</button><button class="secondary" onclick="ttCalToday()">Hoje</button><button class="secondary" onclick="ttCalNext()">›</button></div><div class="tt-caltitle"><strong>${esc(title)}</strong><input type="date" value="${iso(anchor)}" onchange="ttCalGo(this.value)"></div><div class="tt-calactions"><div class="tt-viewtoggle"><button class="${view==='week'?'active':''}" onclick="ttCalView('week')">Semana</button><button class="${view==='month'?'active':''}" onclick="ttCalView('month')">Mês</button></div><button class="primary" onclick="eventModal()">+ Nova marcação</button></div></div>`}
function evCard(e){return`<div class="event ${e.event_type==='Avaliação'?'eval':''}" role="button" tabindex="0" onclick="ttOpenEvent('${e.id}','${e._start.toISOString()}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();ttOpenEvent('${e.id}','${e._start.toISOString()}')}"><strong>${e._start.toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})} · ${esc(student(e.student_id)?.name||'Aluno')}</strong>${esc(e.event_type)}${e.location?`<br>${esc(e.location)}`:''}${e.recurrence!=='none'?`<div class="recurrence-chip">↻ <span class="tt-recur-long">${recur(e.recurrence)}</span><span class="tt-recur-short">${recurShort(e.recurrence)}</span></div>`:''}<div class="event-actions"><button onclick="event.stopPropagation();ttAddCalendar('${e.id}')">📅 PT</button><button onclick="event.stopPropagation();ttShareCalendar('${e.id}')">↗ Aluno</button></div></div>`}
function week(){const a=monday(anchor),b=new Date(a);b.setDate(b.getDate()+6);b.setHours(23,59,59,999);const days=Array.from({length:7},(_,i)=>{const d=new Date(a);d.setDate(d.getDate()+i);return d}),all=events.flatMap(e=>occ(e,a,b)),fmt=new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'short'});return`${toolbar(`${fmt.format(a)} — ${fmt.format(b)} ${b.getFullYear()}`)}<div class="calendar">${days.map(d=>{const list=all.filter(e=>e._start.toDateString()===d.toDateString()).sort((x,y)=>x._start-y._start);return`<div class="day ${d.toDateString()===new Date().toDateString()?'tt-today':''}"><h4>${new Intl.DateTimeFormat('pt-PT',{weekday:'short',day:'2-digit',month:'2-digit'}).format(d)}</h4>${list.map(evCard).join('')||'<div class="stat-note">Sem marcações</div>'}</div>`}).join('')}</div>`}
function month(){const first=new Date(anchor.getFullYear(),anchor.getMonth(),1),start=monday(first),end=new Date(start);end.setDate(end.getDate()+41);end.setHours(23,59,59,999);const all=events.flatMap(e=>occ(e,start,end)),days=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d});return`${toolbar(new Intl.DateTimeFormat('pt-PT',{month:'long',year:'numeric'}).format(anchor))}<div class="tt-month-head">${['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(x=>`<span>${x}</span>`).join('')}</div><div class="tt-month">${days.map(d=>{const list=all.filter(e=>e._start.toDateString()===d.toDateString()).sort((x,y)=>x._start-y._start);return`<button class="tt-mday ${d.getMonth()!==anchor.getMonth()?'out':''} ${d.toDateString()===new Date().toDateString()?'today':''}" onclick="ttCalDay('${iso(d)}')"><span class="tt-daynum">${d.getDate()}</span><div class="tt-mevents">${list.slice(0,3).map(e=>`<span class="tt-mevent" onclick="event.stopPropagation();ttOpenEvent('${e.id}','${e._start.toISOString()}')">${e._start.toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})} ${esc(student(e.student_id)?.name||'Aluno')}</span>`).join('')}${list.length>3?`<span class="tt-more">+${list.length-3}</span>`:''}</div></button>`}).join('')}</div>`}
async function render(){const c=document.querySelector('#content');if(!c)return;const [{data:e,error},{data:s}]=await Promise.all([db.from('traintrack_events').select('*').order('starts_at'),db.from('traintrack_students').select('id,name').eq('archived',false)]);if(error)return toast(error.message,true);events=e||[];students=s||[];c.innerHTML=view==='month'?month():week()}
window.ttCalPrev=()=>{view==='week'?anchor.setDate(anchor.getDate()-7):anchor.setMonth(anchor.getMonth()-1);render()};window.ttCalNext=()=>{view==='week'?anchor.setDate(anchor.getDate()+7):anchor.setMonth(anchor.getMonth()+1);render()};window.ttCalToday=()=>{anchor=new Date();anchor.setHours(12,0,0,0);render()};window.ttCalGo=v=>{if(v){anchor=new Date(`${v}T12:00:00`);render()}};window.ttCalView=v=>{view=v==='month'?'month':'week';render()};window.ttCalDay=v=>{anchor=new Date(`${v}T12:00:00`);view='week';render()};window.ttRenderCalendar=render;
const save=window.ttSaveEvent;if(save)window.ttSaveEvent=async e=>{const when=e?.target?.elements?.starts_at?.value;if(when)anchor=new Date(when);await save(e);setTimeout(render,80)};
})();
